<?php
/**
 * @copyright 2011 City of Bloomington, Indiana
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 * @param Person $this->person
 */
?>
<div id="location-panel">
	<div class="left">
		<?php
			include APPLICATION_HOME.'/blocks/html/people/personInfo.inc';
		?>
	</div>
	<div class="right">
		<?php
		?>
	</div>
</div>
