<?php
define('APPLICATION_NAME','testApp');

/**
 * The URL to get to this site
 * Do NOT use a trailing slash
 */
define('BASE_URL','http://localhost/testApp');
define('BASE_URI','/testApp');

/**
 * Used when there's an error on the site.  The Framework will
 * print out a nice error message, encouraging users to report any problems
 * See: Blossom\Classes\Error
 */
define('ADMINISTRATOR_NAME','Site Admin');
define('ADMINISTRATOR_EMAIL','admin@localhost');

define('DATE_FORMAT', 'n/j/Y H:i:s');
