---
- name: check if ureport apache config already exists
  stat: path=/etc/apache2/sites-available/{{ ureport_name }}.conf
  register: original

# check if backup of ureport_apache_config exists
# if it already exists, we won't move it again
- name: check if ureport apached config backup already exists
  stat: path=/etc/apache2/sites-available/{{ ureport_name }}.bak
  register: backup

#note that "copy" command in ansible copies from ansible client to host
#one machine to the other
#here we just want to do the copy only on the host
- name: Make a backup copy of ureport apache config file
  shell: cp /etc/apache2/sites-available/{{ ureport_name }}.conf /etc/apache2/sites-available/{{ ureport_name }}.bak
  when: original.stat.exists and not backup.stat.exists

- name: Create an apache config file for ureport site based on template
  template: src=ureport.conf dest=/etc/apache2/sites-available/{{ ureport_name }}.conf
  notify:
    - apache_restart
  tags: ureport

- name: a2ensite ureport
  command: a2ensite ureport
  notify:
    - apache_restart
