---
- name: Create database user
  mysql_user:
    name: "{{ ureport_db.username }}"
    password: "{{ ureport_db.password }}"
    priv: "{{ ureport_db.name }}.*:ALL"
    state: present
    config_file: /etc/mysql/debian.cnf

- name: Create database
  mysql_db: name={{ ureport_db.name }} state=present config_file=/etc/mysql/debian.cnf
  register: db

- name: Initialize database
  mysql_db:
    state: import
    name: "{{ ureport_db.name }}"
    target: "{{ ureport_path }}/crm/scripts/mysql.sql"
    config_file: /etc/mysql/debian.cnf
  when: db.changed

- name: Generate createAdminUser script
  template: src=createAdminUser.php dest={{ ureport_path }}/crm/scripts/
  when: db.changed

- name: Create first user!
  shell: php createAdminUser.php
  args:
    chdir: "{{ ureport_path }}/crm/scripts"
  when: db.changed

- name: Delete createAdminUser script
  file:
    path: "{{ ureport_path }}/crm/scripts/createAdminUser.php"
    state: absent
