---
- name: Clone the repository
  become: no
  git:
    repo: https://github.com/City-of-Bloomington/ureport.git
    dest: "{{ ureport_path }}"
    update: yes
  notify: ureport update permissions

- name: Install Core Dependencies
  become: no
  composer:
    command: update
    working_dir: "{{ ureport_path }}/crm"

- name: Install Theme Dependencies
  become: no
  composer:
    command: update
    working_dir: "{{ ureport_path }}/crm/data/Themes/COB"

- name: Install Factory Number One Dependencies
  become: no
  npm:
    path: "{{ ureport_path }}/crm/data/Themes/COB/vendor/City-of-Bloomington/factory-number-one"
    global: no

- name: Build the application
  become: no
  command: "{{ ureport_path }}/build.sh"
  args:
    chdir: "{{ ureport_path }}"

- name: Configure application instance
  template: src=site_config.inc dest={{ ureport_path }}/crm/data/
  notify: ureport update permissions

- name: Configure COB Theme
  template: src=theme_config.inc dest={{ ureport_path }}/crm/data/Themes/COB
  notify: ureport update permissions
