# This is the latest version of Solr known to work with uReport
solr_version: "5.3.1"

ureport_archive_path: "../build/ureport.tar.gz"
ureport_install_path: "/srv/sites/ureport"
ureport_backup_path:  "/srv/backups/ureport"
ureport_site_home:    "{{ ureport_install_path }}/data"

ureport_base_uri: "/ureport"
ureport_base_url: "https://{{ ansible_host }}{{ ureport_base_uri }}"

ureport_max_image_size: "10M"

ureport_db:
  name:     "ureport"
  username: "ureport"
  password: "{{ vault_ureport_db.password }}"
