<footer>
	<p>Copyright &#169; 2011-2016 City of Bloomington, Indiana. All rights reserved.</p>
	<p> Powered by <a href="https://github.com/City-of-Bloomington/uReport">uReport</a>
		version <?php include APPLICATION_HOME.'/VERSION'; ?>
	</p>
	<p> This application is free software; you can redistribute it and/or modify
		it under the terms of the
		<a href="http://www.gnu.org/licenses/agpl.html">GNU Affero General Public License</a>
	</p>
</footer>
