<?php
/**
 * @copyright 2011 City of Bloomington, Indiana
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 * @param Ticket $this->ticket
 */
?>
<div id="ticket-panel">
	<div class="left">
		<?php
			include APPLICATION_HOME.'/blocks/html/tickets/ticketInfo.inc';
		?>
	</div>
	<div class="right">
		<?php

		?>
	</div>
</div>
