- hosts: linux-ureport
  become: yes
  roles:
    - City-of-Bloomington.linux
    - City-of-Bloomington.apache
    - City-of-Bloomington.mysql
    - City-of-Bloomington.php
    - City-of-Bloomington.solr
    - ureport
