<link rel="stylesheet" type="text/css" href="<?= BASE_URI; ?>/css/screen.css" />
<link rel="stylesheet" type="text/css" href="<?= BASE_URI; ?>/css/print.css" media="print">
<link rel="stylesheet" type="text/css" href="<?= JQUERY_UI; ?>/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="<?= $this->theme_config['FN1_URI']; ?>/assets/css/default.css" />
<link rel="stylesheet" type="text/css" href="<?= BASE_URI; ?>/COB/css/screen.css" />
