<link rel="stylesheet" type="text/css" href="<?= BASE_URI; ?>/css/screen.css" />
<link rel="stylesheet" type="text/css" href="<?= BASE_URI; ?>/css/print.css" media="print">
<link rel="stylesheet" type="text/css" href="<?= JQUERY_UI; ?>/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="<?= BASE_URI; ?>/COB/css/screen.css" />
<link rel="stylesheet" type="text/css" href="<?= BASE_URI; ?>/COB/css/font-awesome/css/font-awesome.css" />
<link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700,600" rel="stylesheet" type="text/css">
