<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<?php
	$this->layout = 'twoColumn_400-a';
	$dir = dirname(__FILE__);
	include $dir.'/partials/header.inc';
?>
<body>
	<?php
		include $dir.'/partials/banner.inc';
		include $dir.'/partials/menubar.inc';
	?>
	<div id="panel-container">
		<div id="left" class="panel">
			<?php echo $this->includeBlocks('left'); ?>
		</div>
		<div id="right" class="panel">
			<?php
				include FRAMEWORK.'/errorMessages.php';
				echo $this->includeBlocks('right');
			?>
		</div>
	</div>
	<?php include $dir.'/partials/footer.inc'; ?>
</body>
</html>
<?php
	include $dir.'/partials/garbageCollection.inc';
?>
