<div>
	<h1>Admin</h1>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/users">Users</a></li>
		<li><a href="<?php echo BASE_URL; ?>/departments">Departments</a></li>
		<li><a href="<?php echo BASE_URL; ?>/categories">Categories</a></li>
		<li><a href="<?php echo BASE_URL; ?>/resolutions">Resolutions</a></li>
		<li><a href="<?php echo BASE_URL; ?>/actions">Actions</a></li>
		<li><a href="<?php echo BASE_URL; ?>/clients">Clients</a></li>
		<li><a href="<?php echo BASE_URL; ?>/lookups/labels.php">Labels</a></li>
	</ul>
</div>
