<div>
	<h2>Admin</h2>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/users">Users</a></li>
		<li><a href="<?php echo BASE_URL; ?>/departments">Departments</a></li>
		<li><a href="<?php echo BASE_URL; ?>/categories">Categories</a></li>
		<li><a href="<?php echo BASE_URL; ?>/categoryGroups">Groups</a></li>
		<li><a href="<?php echo BASE_URL; ?>/resolutions">Resolutions</a></li>
		<li><a href="<?php echo BASE_URL; ?>/actions">Actions</a></li>
		<li><a href="<?php echo BASE_URL; ?>/clients">Clients</a></li>
		<li><a href="<?php echo BASE_URL; ?>/labels">Labels</a></li>
		<li><a href="<?php echo BASE_URL; ?>/contactMethods">Contact Methods</a></li>
		<li><a href="<?php echo BASE_URL; ?>/types">Issue Types</a></li>
	</ul>
</div>
