---
solr_version: "5.5.3"

ureport_name: ureport
ureport_version: 2.0.2
ureport_uri: /{{ ureport_name }}
ureport_install_dir: /srv/sites
ureport_path: "{{ ureport_install_dir }}/{{ ureport_name }}"

ureport_db:
  name: "{{ ureport_name }}"
  username: "{{ ureport_name }}"
  password: "{{ vault_ureport_db.password }}"

ureport_admin:
  username: "{{ ansible_user|default(lookup('env', 'USER'), True) }}"
  firstname: "Admin"
  lastname: "Person"
  email: "{{ ansible_user|default(lookup('env', 'USER'), True) }}@localhost"

ureport_directory_server: ''
ureport_cas_server: ''
